### ISSUE TITLE
Building off your project

### ISSUE THREAD

**Issue by generalredneck** [desbma/referer-spam-domains-blacklist#5]
@desbma,
Sorry About opening an issue for this but I wanted you to know that I am using your spammers.txt to help build upon a project that I started yesterday because fail2ban is only half of the work that one needs to do to remove referral spam. You can find my solution that I use in conjunction with yours at https://github.com/generalredneck/ga-referrer-spam-filters. I was wondering if we could do some linkbacks via each other's readme's and if you may be able to help me see if my docs make sense.

There is a little bit more about it on my blog as well at http://generalredneck.com/blog/google-analytics-referral-spam-bots

**Comment by desbma** [comment]
Hi,

What you describe in your blog (that the spammers sometimes spam the Google servers directly with the site ID) is unfortunaly well known for years and Google did nothing to address that.

I don't use Google Analytics that much, and I consider only server side analytics as 100% reliable (GA can also be blocked by ad blockers), but I think your project is a good way to use the list, and I am sure some GA users will find it useful.
I can add a link to your project in the Readme as a possible use of the list.

I update this list regularly with domains that hit my servers (script not in the repo), and to [remove dead domains](https://github.com/desbma/referer-spam-domains-blacklist/blob/master/remove-dead-domains.py).

I also want to mention that this list is also made from contributions from:
- [Piwik's list](https://github.com/piwik/referrer-spam-blacklist) I forked their project because they were updating the list way too conservatively for my needs, but I still merge their list additions regularly
- @Rup0rt [contributed](https://github.com/desbma/referer-spam-domains-blacklist/pull/2/files) a large bunch of domains

Also be careful about [hotlinking from GitHub servers](https://github.com/generalredneck/ga-referrer-spam-filters/blob/cb77419ad42e00416c259a089358b8f487ad7c44/src/Command/UpdateSpamListCommand.php#L38). If you download too much they will block you, so [I had to use git just to download one single file](https://github.com/desbma/referer-spam-domains-blacklist/blob/c55785896061cac5212144f02595e4a2c4dcc42f/update-fail2ban-referer-filter#L27-L31)...
It might not be a problem for a single download from time to time, but just be advised it can fail.

**Comment by generalredneck** [comment]
Awesome.
I'm a newbie in the realm of analytics and will be looking up to see what solutions are out there for server side analytics (besides trying to look through all the log files myself).

As for your approval on the use for the list, I really appreciate that. Your feedback is very constructive. I also appreciate the peer review of the code. When I work for a company, that process is always helpful and I lack that on my personal projects. I will take your suggestions into account. I can probably count on the user having git installed on their machine since they are using composer. but may place backup code to hotlink in the application just in case. Another way to achieve this is using an API token like Composer does. Here's the rules for [Rate Limiting](https://developer.github.com/v3/#rate-limiting). 

Lastly, I think I could avoid all of this by polling for changes once a day and mirroring the list on my own server. This would take away any concern around the need for git or rate limit problems. As it is, I do this once a week with your application anyway :P. 

I truly don't expect any high volume of adoption for this script, as the layman on a windows machine will have a hard time installing and using it as it requires both knowledge of using a console and composer, both very developer focused. Much like your fail2ban filter... Cept you did make it pretty damn simple :+1:
